### ISSUE TITLE
Not deployed to rubygems?

### ISSUE THREAD

**Issue by crystalneth** [imgix/paperclip-imgix#3]
This doesn't seem to be in the rubygems repository, which means it needs to be manually installed, unless it's in another repo (in which case, please specify).

**Comment by kellysutton** [comment]
Unfortunately, this library is no longer maintained. We're looking for better ways of hooking into Paperclip that is more future-proof than this gem. As a result, we're cleaning up this repo and closing all old tickets.

We do have a lighter-weight gem for building and signing imgix URLs, which works well in tandem with normal paperclip. Please check that out here: https://github.com/imgix/imgix-rb
